# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 56abc9e210e8d7af8ad8e385191f2b68dd87d4948be1ee55356e12c7859edb17182bf75cda54cacedb4e7eb49dc20a2f983d7208d3e5e95106576d91a93646a2

test:
  secret_key_base: 9e1d069b07be55ea2cb60b3e1a514ae6117b0a6f1565dae0f1f77fa79c5349dcfd5c9545aa6802f433f439ec2d5a4635e5e4ab4e6c1a5f04fb83ccb4cd42cea8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
